### ISSUE TITLE
finish M1 according to review

### ISSUE THREAD

**Issue by Kayeeec** [Richardb953/Airport-Manager#30]
- opravit `equals` a `hashCode` v
    - [x] Airplane @Kayeeec
    - [x] Airport @xkrejci7
    - [ ] Steward @andrea-n  
    - [equals()/hashCode() článek](http://www.javaranch.com/journal/2002/10/equalhash.html)
- [x] opravit nekonzistentní javadoc ve `Flight` ( `* @param flight Long value of flight id  void removeFlight(Flight flight);"` ) @Richardb953 
- VŠUDE  uvádět `@autor` jméno příjmení + github id 
    - [x] @Kayeeec 
    - [x] @Richardb953  
    - [ ] @andrea-n 
    - [x] @xkrejci7 
- Entity aby vracely List jako unmodifiable
    - [x] Airplane @Kayeeec
    - [ ] Flight @Richardb953 
    - [ ] Steward @andrea-n 
    - [x] Airport @xkrejci7 
- [x] smazat prázdné složky co obsahují jen README ?

**Comment by xkrejci7** [comment]
Airport nema zadnou metodu, ktera by vracela List

**Comment by Richardb953** [comment]
viete mi povedat co to znamena vracat list ako unmodifiable?
