### ISSUE TITLE
Biznis poziadavky - facade layer

### ISSUE THREAD

**Issue by Richardb953** [Richardb953/Airport-Manager#36]
Precitajte si na wiki:
https://github.com/Richardb953/Airport-Manager/wiki/Biznis-poziadavky-na-system
a sem do komentara tejto issue napiste co vam pride relevantne / nerelevantne riesit, aby sme to nemuseli hladat potom v konverzacii na Google. 
Skuste napisat ake biznis problemy mate v plane riesit / neriesit.
A nezabudajte na jednu vec: kedze mam na starosti Flight tak pre jeho vytvorenie som zavisli dost od vas. a musime to rozdelit nejako tak aby som neriesil celu logiku ja.... ak mate nejake rozumne navrhy sem s nimi.
pointa je spravit to tak aby sme riesili kazdy 2-3 biznis casy ale tak aby som ja vo flight nemusel dorabat nic u vas, lebo by mi tam chybala daka podstatna informacia

**Comment by xkrejci7** [comment]
Kde jsi prisel na ty business casy?
Nemuze nas vic pracovat na Flight?

**Comment by Richardb953** [comment]
zadanie znie:
Create an information system managing flight records at an airport. The system should allow the users to enter records about stewards, airplanes and destinations. It should also be possible to update and delete these records. A destination should contain at least the information about the location of an airport (country, city). Airplane details should contain the capacity of the plane and its name (and possibly its type as well). A steward is described by his first and last name. The system should also allow us to record a flight. When recording a flight, it is necessary to set the departure and arrival times, the origin, the destination and the plane. The system should also check that the plane does not have another flight scheduled during the time of the this flight. It should also be possible to assign (remove) stewards to (from) a flight while checking for the steward's availability. The ultimate goal is to have a system capable of listing flights ordered by date and displaying the flight details (origin, destination, departure time, arrival time, plane, list of stewards).

ak si to precitas tak vies z toho urcit co sa od toho systemu ocakava, tak som skusil najst problemy s tym suvisiace

**Comment by Kayeeec** [comment]
Z toho co jsem tu četla v podstatě musíme vyřešit jak implementovat 2 funkce co by mohly vypadat přibližně takto:
```
List<Steward> getAvailableStewards(Flight flight)
List<Airplane> getAvailableAirplanes(Flight flight)
```
* pro zadaný `flight` vrátí všechny dostupné stewardy/letadla
* `flight` musí mít zadány atributy - odkud, kam, čas odletu a čas příletu
* steward/letadlo je dostupný pokud:
    * se v době odletu nachází v místě odletu **`AND`**
    * v intervalu letu nemá žádný jiný let **`AND`**
    * místo příletu nekoliduje s následujícím letem - to znamená  že pokud v atributu `flights` je let který by následoval po tomto, ten následující let musí začínat tam kde předchozí skončil - pro lepší pochopení to napíšu v pseudokódu _(je to jen příklad, neřešte že nepoužívám gettry a equals :-)_:
        * `flight.destinationPort == nextFlight.sourcePort`

* pro jednoduchost bychom si mohli určit že pokud by atribut `flights` u stewarda/letadla byl prázdný, tak je steward/letadlo dostupné 

A teď kde je implementovat a kde se budou používat, nějaké nápady?

V entitách Steward a Airport bychom mohli implementovat pomocné funkce, něco jako:
`boolean checkIfAvailable(Flight flight) `  
- vrací `true` pokud je steward/letadlo pro daný flight dostupný

**Comment by andrea-n** [comment]
Kde implementovat tyhle dvě funkce - napadá mě, co je dát na letiště - stewardi a letadla jsou zaparkovaní na letišti, tak getAvailableStewards/Airplanes(Flight flight) možná dát tam. Nebo by se to mohlo dát bez parametru na flight?
